//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevinoSmsService.DevinoViber {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MessageStateInfo", Namespace="http://ws.devinosms.com")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(DevinoSmsService.DevinoViber.SmsMessageStateInfo))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(DevinoSmsService.DevinoViber.ViberSmsMessageStateInfo))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(DevinoSmsService.DevinoViber.ViberMessageStateInfo))]
    public partial class MessageStateInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.Nullable<System.DateTime> CreationDateUtcField;
        
        private System.Nullable<System.DateTime> SubmittedDateUtcField;
        
        private System.Nullable<System.DateTime> ReportedDateUtcField;
        
        private System.DateTime TimeStampUtcField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StateDescriptionField;
        
        private System.Nullable<decimal> PriceField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<System.DateTime> CreationDateUtc {
            get {
                return this.CreationDateUtcField;
            }
            set {
                if ((this.CreationDateUtcField.Equals(value) != true)) {
                    this.CreationDateUtcField = value;
                    this.RaisePropertyChanged("CreationDateUtc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<System.DateTime> SubmittedDateUtc {
            get {
                return this.SubmittedDateUtcField;
            }
            set {
                if ((this.SubmittedDateUtcField.Equals(value) != true)) {
                    this.SubmittedDateUtcField = value;
                    this.RaisePropertyChanged("SubmittedDateUtc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public System.Nullable<System.DateTime> ReportedDateUtc {
            get {
                return this.ReportedDateUtcField;
            }
            set {
                if ((this.ReportedDateUtcField.Equals(value) != true)) {
                    this.ReportedDateUtcField = value;
                    this.RaisePropertyChanged("ReportedDateUtc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public System.DateTime TimeStampUtc {
            get {
                return this.TimeStampUtcField;
            }
            set {
                if ((this.TimeStampUtcField.Equals(value) != true)) {
                    this.TimeStampUtcField = value;
                    this.RaisePropertyChanged("TimeStampUtc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string StateDescription {
            get {
                return this.StateDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.StateDescriptionField, value) != true)) {
                    this.StateDescriptionField = value;
                    this.RaisePropertyChanged("StateDescription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public System.Nullable<decimal> Price {
            get {
                return this.PriceField;
            }
            set {
                if ((this.PriceField.Equals(value) != true)) {
                    this.PriceField = value;
                    this.RaisePropertyChanged("Price");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SmsMessageStateInfo", Namespace="http://ws.devinosms.com")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(DevinoSmsService.DevinoViber.ViberSmsMessageStateInfo))]
    public partial class SmsMessageStateInfo : DevinoSmsService.DevinoViber.MessageStateInfo {
        
        private DevinoSmsService.DevinoViber.MessageState StateField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public DevinoSmsService.DevinoViber.MessageState State {
            get {
                return this.StateField;
            }
            set {
                if ((this.StateField.Equals(value) != true)) {
                    this.StateField = value;
                    this.RaisePropertyChanged("State");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ViberSmsMessageStateInfo", Namespace="http://ws.devinosms.com")]
    [System.SerializableAttribute()]
    public partial class ViberSmsMessageStateInfo : DevinoSmsService.DevinoViber.SmsMessageStateInfo {
        
        private long IdField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ViberMessageStateInfo", Namespace="http://ws.devinosms.com")]
    [System.SerializableAttribute()]
    public partial class ViberMessageStateInfo : DevinoSmsService.DevinoViber.MessageStateInfo {
        
        private DevinoSmsService.DevinoViber.InstantMessageStatus StateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DevinoSmsService.DevinoViber.ViberSmsMessageStateInfo[] ResentSmsField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public DevinoSmsService.DevinoViber.InstantMessageStatus State {
            get {
                return this.StateField;
            }
            set {
                if ((this.StateField.Equals(value) != true)) {
                    this.StateField = value;
                    this.RaisePropertyChanged("State");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public DevinoSmsService.DevinoViber.ViberSmsMessageStateInfo[] ResentSms {
            get {
                return this.ResentSmsField;
            }
            set {
                if ((object.ReferenceEquals(this.ResentSmsField, value) != true)) {
                    this.ResentSmsField = value;
                    this.RaisePropertyChanged("ResentSms");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InstantMessageStatus", Namespace="http://ws.devinosms.com")]
    public enum InstantMessageStatus : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Enqueued = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Sent = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Delivered = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Read = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Undelivered = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Failed = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Unknown = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Expired = 7,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MessageState", Namespace="http://ws.devinosms.com")]
    public enum MessageState : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Optimized = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Errors = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Tarificated = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        StopListRejected = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DuplicateRejected = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PolicyRejected = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ErrorSendingDateTimeInterpretation = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Sent = 7,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LocalQueued = 8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Parked = 9,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Queued = 10,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Sending_To_Gateway = 11,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Sending_To_Recipient = 12,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SentFromQueue = 13,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Delivered_To_Recipient = 14,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Error_Invalid_Destination_Address = 15,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Error_Invalid_Source_Address = 16,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Error_Incompatible_Destination = 17,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Error_Rejected = 18,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Error_Expired = 19,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Deleted = 20,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Devino_Rejected = 21,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Unknown = 22,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Message_Length_is_invalid = 23,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Command_Length_is_invalid = 24,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Invalid_Command_ID = 25,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Incorrect_BIND_Status_for_given_command = 26,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ESME_Already_in_Bound_State = 27,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Invalid_Priority_Flag = 28,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Invalid_Registered_Delivery_Flag = 29,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        System_Error = 30,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Message_ID_is_invalid = 31,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Bind_Failed = 32,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Invalid_Password = 33,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Invalid_System_ID = 34,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Cancel_SM_Failed = 35,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Replace_SM_Failed = 36,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Message_Queue_Full = 37,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Invalid_Service_Type = 38,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Invalid_number_of_destinations = 39,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Invalid_Distribution_List_name = 40,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Destination_flag_is_invalid = 41,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Invalid_request = 42,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Invalid_esm_class_field_data = 43,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Cannot_Submit_to_Distribution_List = 44,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        submit_sm_or_submit_multi_failed = 45,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Invalid_Source_address_TON = 46,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Invalid_Source_address_NPI = 47,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Invalid_Destination_address_TON = 48,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Invalid_Destination_address_NPI = 49,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Invalid_system_type_field = 50,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Invalid_replace_if_present_flag = 51,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Invalid_number_of_messages = 52,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Throttling_error = 53,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Invalid_Scheduled_Delivery_Time = 54,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Invalid_message_validity_period = 55,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Predefined_Message_Invalid_or_Not_Found = 56,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ESME_Receiver_Temporary_App_Error_Code = 57,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ESME_Receiver_Permanent_App_Error_Code = 58,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ESME_Receiver_Reject_Message_Error_Code = 59,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        query_sm_request_failed = 60,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Error_in_the_optional_part_of_the_PDU_Body = 61,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Optional_Parameter_not_allowed = 62,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Invalid_Parameter_Length = 63,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Expected_Optional_Parameter_missing = 64,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Invalid_Optional_Parameter_Value = 65,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Delivery_Failure = 66,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Message", Namespace="http://ws.devinosms.com")]
    [System.SerializableAttribute()]
    public partial class Message : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DataField;
        
        private System.Nullable<System.DateTime> DelayUntilUtcField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DevinoSmsService.DevinoViber.ArrayOfString DestinationAddressesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SourceAddressField;
        
        private bool ReceiptRequestedField;
        
        private System.Nullable<int> ValidityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DevinoSmsService.DevinoViber.ArrayOfString OptionalsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Data {
            get {
                return this.DataField;
            }
            set {
                if ((object.ReferenceEquals(this.DataField, value) != true)) {
                    this.DataField = value;
                    this.RaisePropertyChanged("Data");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<System.DateTime> DelayUntilUtc {
            get {
                return this.DelayUntilUtcField;
            }
            set {
                if ((this.DelayUntilUtcField.Equals(value) != true)) {
                    this.DelayUntilUtcField = value;
                    this.RaisePropertyChanged("DelayUntilUtc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public DevinoSmsService.DevinoViber.ArrayOfString DestinationAddresses {
            get {
                return this.DestinationAddressesField;
            }
            set {
                if ((object.ReferenceEquals(this.DestinationAddressesField, value) != true)) {
                    this.DestinationAddressesField = value;
                    this.RaisePropertyChanged("DestinationAddresses");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string SourceAddress {
            get {
                return this.SourceAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.SourceAddressField, value) != true)) {
                    this.SourceAddressField = value;
                    this.RaisePropertyChanged("SourceAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public bool ReceiptRequested {
            get {
                return this.ReceiptRequestedField;
            }
            set {
                if ((this.ReceiptRequestedField.Equals(value) != true)) {
                    this.ReceiptRequestedField = value;
                    this.RaisePropertyChanged("ReceiptRequested");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public System.Nullable<int> Validity {
            get {
                return this.ValidityField;
            }
            set {
                if ((this.ValidityField.Equals(value) != true)) {
                    this.ValidityField = value;
                    this.RaisePropertyChanged("Validity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public DevinoSmsService.DevinoViber.ArrayOfString Optionals {
            get {
                return this.OptionalsField;
            }
            set {
                if ((object.ReferenceEquals(this.OptionalsField, value) != true)) {
                    this.OptionalsField = value;
                    this.RaisePropertyChanged("Optionals");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://ws.devinosms.com", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ws.devinosms.com", ConfigurationName="DevinoViber.ViberServiceSoap")]
    public interface ViberServiceSoap {
        
        // CODEGEN: Generating message contract since element name sessionID from namespace http://ws.devinosms.com is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.devinosms.com/GetMessageState", ReplyAction="*")]
        DevinoSmsService.DevinoViber.GetMessageStateResponse GetMessageState(DevinoSmsService.DevinoViber.GetMessageStateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.devinosms.com/GetMessageState", ReplyAction="*")]
        System.Threading.Tasks.Task<DevinoSmsService.DevinoViber.GetMessageStateResponse> GetMessageStateAsync(DevinoSmsService.DevinoViber.GetMessageStateRequest request);
        
        // CODEGEN: Generating message contract since element name login from namespace http://ws.devinosms.com is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.devinosms.com/GetSessionID", ReplyAction="*")]
        DevinoSmsService.DevinoViber.GetSessionIDResponse GetSessionID(DevinoSmsService.DevinoViber.GetSessionIDRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.devinosms.com/GetSessionID", ReplyAction="*")]
        System.Threading.Tasks.Task<DevinoSmsService.DevinoViber.GetSessionIDResponse> GetSessionIDAsync(DevinoSmsService.DevinoViber.GetSessionIDRequest request);
        
        // CODEGEN: Generating message contract since element name sessionID from namespace http://ws.devinosms.com is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.devinosms.com/SendMessage", ReplyAction="*")]
        DevinoSmsService.DevinoViber.SendMessageResponse SendMessage(DevinoSmsService.DevinoViber.SendMessageRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.devinosms.com/SendMessage", ReplyAction="*")]
        System.Threading.Tasks.Task<DevinoSmsService.DevinoViber.SendMessageResponse> SendMessageAsync(DevinoSmsService.DevinoViber.SendMessageRequest request);
        
        // CODEGEN: Generating message contract since element name sessionID from namespace http://ws.devinosms.com is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.devinosms.com/SendMessageWithResend", ReplyAction="*")]
        DevinoSmsService.DevinoViber.SendMessageWithResendResponse SendMessageWithResend(DevinoSmsService.DevinoViber.SendMessageWithResendRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.devinosms.com/SendMessageWithResend", ReplyAction="*")]
        System.Threading.Tasks.Task<DevinoSmsService.DevinoViber.SendMessageWithResendResponse> SendMessageWithResendAsync(DevinoSmsService.DevinoViber.SendMessageWithResendRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetMessageStateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetMessageState", Namespace="http://ws.devinosms.com", Order=0)]
        public DevinoSmsService.DevinoViber.GetMessageStateRequestBody Body;
        
        public GetMessageStateRequest() {
        }
        
        public GetMessageStateRequest(DevinoSmsService.DevinoViber.GetMessageStateRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ws.devinosms.com")]
    public partial class GetMessageStateRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sessionID;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public long messageID;
        
        public GetMessageStateRequestBody() {
        }
        
        public GetMessageStateRequestBody(string sessionID, long messageID) {
            this.sessionID = sessionID;
            this.messageID = messageID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetMessageStateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetMessageStateResponse", Namespace="http://ws.devinosms.com", Order=0)]
        public DevinoSmsService.DevinoViber.GetMessageStateResponseBody Body;
        
        public GetMessageStateResponse() {
        }
        
        public GetMessageStateResponse(DevinoSmsService.DevinoViber.GetMessageStateResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ws.devinosms.com")]
    public partial class GetMessageStateResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public DevinoSmsService.DevinoViber.ViberMessageStateInfo GetMessageStateResult;
        
        public GetMessageStateResponseBody() {
        }
        
        public GetMessageStateResponseBody(DevinoSmsService.DevinoViber.ViberMessageStateInfo GetMessageStateResult) {
            this.GetMessageStateResult = GetMessageStateResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetSessionIDRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetSessionID", Namespace="http://ws.devinosms.com", Order=0)]
        public DevinoSmsService.DevinoViber.GetSessionIDRequestBody Body;
        
        public GetSessionIDRequest() {
        }
        
        public GetSessionIDRequest(DevinoSmsService.DevinoViber.GetSessionIDRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ws.devinosms.com")]
    public partial class GetSessionIDRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string login;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        public GetSessionIDRequestBody() {
        }
        
        public GetSessionIDRequestBody(string login, string password) {
            this.login = login;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetSessionIDResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetSessionIDResponse", Namespace="http://ws.devinosms.com", Order=0)]
        public DevinoSmsService.DevinoViber.GetSessionIDResponseBody Body;
        
        public GetSessionIDResponse() {
        }
        
        public GetSessionIDResponse(DevinoSmsService.DevinoViber.GetSessionIDResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ws.devinosms.com")]
    public partial class GetSessionIDResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetSessionIDResult;
        
        public GetSessionIDResponseBody() {
        }
        
        public GetSessionIDResponseBody(string GetSessionIDResult) {
            this.GetSessionIDResult = GetSessionIDResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendMessageRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendMessage", Namespace="http://ws.devinosms.com", Order=0)]
        public DevinoSmsService.DevinoViber.SendMessageRequestBody Body;
        
        public SendMessageRequest() {
        }
        
        public SendMessageRequest(DevinoSmsService.DevinoViber.SendMessageRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ws.devinosms.com")]
    public partial class SendMessageRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sessionID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public DevinoSmsService.DevinoViber.Message message;
        
        public SendMessageRequestBody() {
        }
        
        public SendMessageRequestBody(string sessionID, DevinoSmsService.DevinoViber.Message message) {
            this.sessionID = sessionID;
            this.message = message;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendMessageResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendMessageResponse", Namespace="http://ws.devinosms.com", Order=0)]
        public DevinoSmsService.DevinoViber.SendMessageResponseBody Body;
        
        public SendMessageResponse() {
        }
        
        public SendMessageResponse(DevinoSmsService.DevinoViber.SendMessageResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ws.devinosms.com")]
    public partial class SendMessageResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public DevinoSmsService.DevinoViber.ArrayOfString SendMessageResult;
        
        public SendMessageResponseBody() {
        }
        
        public SendMessageResponseBody(DevinoSmsService.DevinoViber.ArrayOfString SendMessageResult) {
            this.SendMessageResult = SendMessageResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendMessageWithResendRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendMessageWithResend", Namespace="http://ws.devinosms.com", Order=0)]
        public DevinoSmsService.DevinoViber.SendMessageWithResendRequestBody Body;
        
        public SendMessageWithResendRequest() {
        }
        
        public SendMessageWithResendRequest(DevinoSmsService.DevinoViber.SendMessageWithResendRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ws.devinosms.com")]
    public partial class SendMessageWithResendRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sessionID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public DevinoSmsService.DevinoViber.Message message;
        
        public SendMessageWithResendRequestBody() {
        }
        
        public SendMessageWithResendRequestBody(string sessionID, DevinoSmsService.DevinoViber.Message message) {
            this.sessionID = sessionID;
            this.message = message;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendMessageWithResendResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendMessageWithResendResponse", Namespace="http://ws.devinosms.com", Order=0)]
        public DevinoSmsService.DevinoViber.SendMessageWithResendResponseBody Body;
        
        public SendMessageWithResendResponse() {
        }
        
        public SendMessageWithResendResponse(DevinoSmsService.DevinoViber.SendMessageWithResendResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ws.devinosms.com")]
    public partial class SendMessageWithResendResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public DevinoSmsService.DevinoViber.ArrayOfString SendMessageWithResendResult;
        
        public SendMessageWithResendResponseBody() {
        }
        
        public SendMessageWithResendResponseBody(DevinoSmsService.DevinoViber.ArrayOfString SendMessageWithResendResult) {
            this.SendMessageWithResendResult = SendMessageWithResendResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ViberServiceSoapChannel : DevinoSmsService.DevinoViber.ViberServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ViberServiceSoapClient : System.ServiceModel.ClientBase<DevinoSmsService.DevinoViber.ViberServiceSoap>, DevinoSmsService.DevinoViber.ViberServiceSoap {
        
        public ViberServiceSoapClient() {
        }
        
        public ViberServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ViberServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ViberServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ViberServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DevinoSmsService.DevinoViber.GetMessageStateResponse DevinoSmsService.DevinoViber.ViberServiceSoap.GetMessageState(DevinoSmsService.DevinoViber.GetMessageStateRequest request) {
            return base.Channel.GetMessageState(request);
        }
        
        public DevinoSmsService.DevinoViber.ViberMessageStateInfo GetMessageState(string sessionID, long messageID) {
            DevinoSmsService.DevinoViber.GetMessageStateRequest inValue = new DevinoSmsService.DevinoViber.GetMessageStateRequest();
            inValue.Body = new DevinoSmsService.DevinoViber.GetMessageStateRequestBody();
            inValue.Body.sessionID = sessionID;
            inValue.Body.messageID = messageID;
            DevinoSmsService.DevinoViber.GetMessageStateResponse retVal = ((DevinoSmsService.DevinoViber.ViberServiceSoap)(this)).GetMessageState(inValue);
            return retVal.Body.GetMessageStateResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DevinoSmsService.DevinoViber.GetMessageStateResponse> DevinoSmsService.DevinoViber.ViberServiceSoap.GetMessageStateAsync(DevinoSmsService.DevinoViber.GetMessageStateRequest request) {
            return base.Channel.GetMessageStateAsync(request);
        }
        
        public System.Threading.Tasks.Task<DevinoSmsService.DevinoViber.GetMessageStateResponse> GetMessageStateAsync(string sessionID, long messageID) {
            DevinoSmsService.DevinoViber.GetMessageStateRequest inValue = new DevinoSmsService.DevinoViber.GetMessageStateRequest();
            inValue.Body = new DevinoSmsService.DevinoViber.GetMessageStateRequestBody();
            inValue.Body.sessionID = sessionID;
            inValue.Body.messageID = messageID;
            return ((DevinoSmsService.DevinoViber.ViberServiceSoap)(this)).GetMessageStateAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DevinoSmsService.DevinoViber.GetSessionIDResponse DevinoSmsService.DevinoViber.ViberServiceSoap.GetSessionID(DevinoSmsService.DevinoViber.GetSessionIDRequest request) {
            return base.Channel.GetSessionID(request);
        }
        
        public string GetSessionID(string login, string password) {
            DevinoSmsService.DevinoViber.GetSessionIDRequest inValue = new DevinoSmsService.DevinoViber.GetSessionIDRequest();
            inValue.Body = new DevinoSmsService.DevinoViber.GetSessionIDRequestBody();
            inValue.Body.login = login;
            inValue.Body.password = password;
            DevinoSmsService.DevinoViber.GetSessionIDResponse retVal = ((DevinoSmsService.DevinoViber.ViberServiceSoap)(this)).GetSessionID(inValue);
            return retVal.Body.GetSessionIDResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DevinoSmsService.DevinoViber.GetSessionIDResponse> DevinoSmsService.DevinoViber.ViberServiceSoap.GetSessionIDAsync(DevinoSmsService.DevinoViber.GetSessionIDRequest request) {
            return base.Channel.GetSessionIDAsync(request);
        }
        
        public System.Threading.Tasks.Task<DevinoSmsService.DevinoViber.GetSessionIDResponse> GetSessionIDAsync(string login, string password) {
            DevinoSmsService.DevinoViber.GetSessionIDRequest inValue = new DevinoSmsService.DevinoViber.GetSessionIDRequest();
            inValue.Body = new DevinoSmsService.DevinoViber.GetSessionIDRequestBody();
            inValue.Body.login = login;
            inValue.Body.password = password;
            return ((DevinoSmsService.DevinoViber.ViberServiceSoap)(this)).GetSessionIDAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DevinoSmsService.DevinoViber.SendMessageResponse DevinoSmsService.DevinoViber.ViberServiceSoap.SendMessage(DevinoSmsService.DevinoViber.SendMessageRequest request) {
            return base.Channel.SendMessage(request);
        }
        
        public DevinoSmsService.DevinoViber.ArrayOfString SendMessage(string sessionID, DevinoSmsService.DevinoViber.Message message) {
            DevinoSmsService.DevinoViber.SendMessageRequest inValue = new DevinoSmsService.DevinoViber.SendMessageRequest();
            inValue.Body = new DevinoSmsService.DevinoViber.SendMessageRequestBody();
            inValue.Body.sessionID = sessionID;
            inValue.Body.message = message;
            DevinoSmsService.DevinoViber.SendMessageResponse retVal = ((DevinoSmsService.DevinoViber.ViberServiceSoap)(this)).SendMessage(inValue);
            return retVal.Body.SendMessageResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DevinoSmsService.DevinoViber.SendMessageResponse> DevinoSmsService.DevinoViber.ViberServiceSoap.SendMessageAsync(DevinoSmsService.DevinoViber.SendMessageRequest request) {
            return base.Channel.SendMessageAsync(request);
        }
        
        public System.Threading.Tasks.Task<DevinoSmsService.DevinoViber.SendMessageResponse> SendMessageAsync(string sessionID, DevinoSmsService.DevinoViber.Message message) {
            DevinoSmsService.DevinoViber.SendMessageRequest inValue = new DevinoSmsService.DevinoViber.SendMessageRequest();
            inValue.Body = new DevinoSmsService.DevinoViber.SendMessageRequestBody();
            inValue.Body.sessionID = sessionID;
            inValue.Body.message = message;
            return ((DevinoSmsService.DevinoViber.ViberServiceSoap)(this)).SendMessageAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DevinoSmsService.DevinoViber.SendMessageWithResendResponse DevinoSmsService.DevinoViber.ViberServiceSoap.SendMessageWithResend(DevinoSmsService.DevinoViber.SendMessageWithResendRequest request) {
            return base.Channel.SendMessageWithResend(request);
        }
        
        public DevinoSmsService.DevinoViber.ArrayOfString SendMessageWithResend(string sessionID, DevinoSmsService.DevinoViber.Message message) {
            DevinoSmsService.DevinoViber.SendMessageWithResendRequest inValue = new DevinoSmsService.DevinoViber.SendMessageWithResendRequest();
            inValue.Body = new DevinoSmsService.DevinoViber.SendMessageWithResendRequestBody();
            inValue.Body.sessionID = sessionID;
            inValue.Body.message = message;
            DevinoSmsService.DevinoViber.SendMessageWithResendResponse retVal = ((DevinoSmsService.DevinoViber.ViberServiceSoap)(this)).SendMessageWithResend(inValue);
            return retVal.Body.SendMessageWithResendResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DevinoSmsService.DevinoViber.SendMessageWithResendResponse> DevinoSmsService.DevinoViber.ViberServiceSoap.SendMessageWithResendAsync(DevinoSmsService.DevinoViber.SendMessageWithResendRequest request) {
            return base.Channel.SendMessageWithResendAsync(request);
        }
        
        public System.Threading.Tasks.Task<DevinoSmsService.DevinoViber.SendMessageWithResendResponse> SendMessageWithResendAsync(string sessionID, DevinoSmsService.DevinoViber.Message message) {
            DevinoSmsService.DevinoViber.SendMessageWithResendRequest inValue = new DevinoSmsService.DevinoViber.SendMessageWithResendRequest();
            inValue.Body = new DevinoSmsService.DevinoViber.SendMessageWithResendRequestBody();
            inValue.Body.sessionID = sessionID;
            inValue.Body.message = message;
            return ((DevinoSmsService.DevinoViber.ViberServiceSoap)(this)).SendMessageWithResendAsync(inValue);
        }
    }
}
