//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevinoSender.DevinoSms {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SmsMessageStateInfo", Namespace="http://ws.devinosms.com")]
    [System.SerializableAttribute()]
    public partial class SmsMessageStateInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.Nullable<System.DateTime> CreationDateUtcField;
        
        private System.Nullable<System.DateTime> SubmittedDateUtcField;
        
        private System.Nullable<System.DateTime> ReportedDateUtcField;
        
        private System.DateTime TimeStampUtcField;
        
        private int StateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StateDescriptionField;
        
        private System.Nullable<decimal> PriceField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<System.DateTime> CreationDateUtc {
            get {
                return this.CreationDateUtcField;
            }
            set {
                if ((this.CreationDateUtcField.Equals(value) != true)) {
                    this.CreationDateUtcField = value;
                    this.RaisePropertyChanged("CreationDateUtc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<System.DateTime> SubmittedDateUtc {
            get {
                return this.SubmittedDateUtcField;
            }
            set {
                if ((this.SubmittedDateUtcField.Equals(value) != true)) {
                    this.SubmittedDateUtcField = value;
                    this.RaisePropertyChanged("SubmittedDateUtc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public System.Nullable<System.DateTime> ReportedDateUtc {
            get {
                return this.ReportedDateUtcField;
            }
            set {
                if ((this.ReportedDateUtcField.Equals(value) != true)) {
                    this.ReportedDateUtcField = value;
                    this.RaisePropertyChanged("ReportedDateUtc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public System.DateTime TimeStampUtc {
            get {
                return this.TimeStampUtcField;
            }
            set {
                if ((this.TimeStampUtcField.Equals(value) != true)) {
                    this.TimeStampUtcField = value;
                    this.RaisePropertyChanged("TimeStampUtc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public int State {
            get {
                return this.StateField;
            }
            set {
                if ((this.StateField.Equals(value) != true)) {
                    this.StateField = value;
                    this.RaisePropertyChanged("State");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string StateDescription {
            get {
                return this.StateDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.StateDescriptionField, value) != true)) {
                    this.StateDescriptionField = value;
                    this.RaisePropertyChanged("StateDescription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public System.Nullable<decimal> Price {
            get {
                return this.PriceField;
            }
            set {
                if ((this.PriceField.Equals(value) != true)) {
                    this.PriceField = value;
                    this.RaisePropertyChanged("Price");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Message", Namespace="http://ws.devinosms.com")]
    [System.SerializableAttribute()]
    public partial class Message : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DataField;
        
        private System.Nullable<System.DateTime> DelayUntilUtcField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DevinoSender.DevinoSms.ArrayOfString DestinationAddressesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SourceAddressField;
        
        private bool ReceiptRequestedField;
        
        private System.Nullable<int> ValidityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DevinoSender.DevinoSms.ArrayOfString OptionalsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Data {
            get {
                return this.DataField;
            }
            set {
                if ((object.ReferenceEquals(this.DataField, value) != true)) {
                    this.DataField = value;
                    this.RaisePropertyChanged("Data");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<System.DateTime> DelayUntilUtc {
            get {
                return this.DelayUntilUtcField;
            }
            set {
                if ((this.DelayUntilUtcField.Equals(value) != true)) {
                    this.DelayUntilUtcField = value;
                    this.RaisePropertyChanged("DelayUntilUtc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public DevinoSender.DevinoSms.ArrayOfString DestinationAddresses {
            get {
                return this.DestinationAddressesField;
            }
            set {
                if ((object.ReferenceEquals(this.DestinationAddressesField, value) != true)) {
                    this.DestinationAddressesField = value;
                    this.RaisePropertyChanged("DestinationAddresses");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string SourceAddress {
            get {
                return this.SourceAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.SourceAddressField, value) != true)) {
                    this.SourceAddressField = value;
                    this.RaisePropertyChanged("SourceAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public bool ReceiptRequested {
            get {
                return this.ReceiptRequestedField;
            }
            set {
                if ((this.ReceiptRequestedField.Equals(value) != true)) {
                    this.ReceiptRequestedField = value;
                    this.RaisePropertyChanged("ReceiptRequested");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public System.Nullable<int> Validity {
            get {
                return this.ValidityField;
            }
            set {
                if ((this.ValidityField.Equals(value) != true)) {
                    this.ValidityField = value;
                    this.RaisePropertyChanged("Validity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public DevinoSender.DevinoSms.ArrayOfString Optionals {
            get {
                return this.OptionalsField;
            }
            set {
                if ((object.ReferenceEquals(this.OptionalsField, value) != true)) {
                    this.OptionalsField = value;
                    this.RaisePropertyChanged("Optionals");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://ws.devinosms.com", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="IncomingMessage", Namespace="http://ws.devinosms.com")]
    [System.SerializableAttribute()]
    public partial class IncomingMessage : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private long IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SourceAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DestinationAddressField;
        
        private System.DateTime CreatedDateUtcField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Data {
            get {
                return this.DataField;
            }
            set {
                if ((object.ReferenceEquals(this.DataField, value) != true)) {
                    this.DataField = value;
                    this.RaisePropertyChanged("Data");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string SourceAddress {
            get {
                return this.SourceAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.SourceAddressField, value) != true)) {
                    this.SourceAddressField = value;
                    this.RaisePropertyChanged("SourceAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string DestinationAddress {
            get {
                return this.DestinationAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.DestinationAddressField, value) != true)) {
                    this.DestinationAddressField = value;
                    this.RaisePropertyChanged("DestinationAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public System.DateTime CreatedDateUtc {
            get {
                return this.CreatedDateUtcField;
            }
            set {
                if ((this.CreatedDateUtcField.Equals(value) != true)) {
                    this.CreatedDateUtcField = value;
                    this.RaisePropertyChanged("CreatedDateUtc");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DeliveryStatistics", Namespace="http://ws.devinosms.com")]
    [System.SerializableAttribute()]
    public partial class DeliveryStatistics : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int SentField;
        
        private int DeliveredField;
        
        private int ErrorsField;
        
        private int InProcessField;
        
        private int ExpiredField;
        
        private int RejectedField;
        
        private int OptimizedField;
        
        private int TarificatedField;
        
        private int TotalField;
        
        private int TotalWithErrorsField;
        
        private decimal DeliveryRatioField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Sent {
            get {
                return this.SentField;
            }
            set {
                if ((this.SentField.Equals(value) != true)) {
                    this.SentField = value;
                    this.RaisePropertyChanged("Sent");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public int Delivered {
            get {
                return this.DeliveredField;
            }
            set {
                if ((this.DeliveredField.Equals(value) != true)) {
                    this.DeliveredField = value;
                    this.RaisePropertyChanged("Delivered");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int Errors {
            get {
                return this.ErrorsField;
            }
            set {
                if ((this.ErrorsField.Equals(value) != true)) {
                    this.ErrorsField = value;
                    this.RaisePropertyChanged("Errors");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int InProcess {
            get {
                return this.InProcessField;
            }
            set {
                if ((this.InProcessField.Equals(value) != true)) {
                    this.InProcessField = value;
                    this.RaisePropertyChanged("InProcess");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public int Expired {
            get {
                return this.ExpiredField;
            }
            set {
                if ((this.ExpiredField.Equals(value) != true)) {
                    this.ExpiredField = value;
                    this.RaisePropertyChanged("Expired");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public int Rejected {
            get {
                return this.RejectedField;
            }
            set {
                if ((this.RejectedField.Equals(value) != true)) {
                    this.RejectedField = value;
                    this.RaisePropertyChanged("Rejected");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public int Optimized {
            get {
                return this.OptimizedField;
            }
            set {
                if ((this.OptimizedField.Equals(value) != true)) {
                    this.OptimizedField = value;
                    this.RaisePropertyChanged("Optimized");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public int Tarificated {
            get {
                return this.TarificatedField;
            }
            set {
                if ((this.TarificatedField.Equals(value) != true)) {
                    this.TarificatedField = value;
                    this.RaisePropertyChanged("Tarificated");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public int Total {
            get {
                return this.TotalField;
            }
            set {
                if ((this.TotalField.Equals(value) != true)) {
                    this.TotalField = value;
                    this.RaisePropertyChanged("Total");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=9)]
        public int TotalWithErrors {
            get {
                return this.TotalWithErrorsField;
            }
            set {
                if ((this.TotalWithErrorsField.Equals(value) != true)) {
                    this.TotalWithErrorsField = value;
                    this.RaisePropertyChanged("TotalWithErrors");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=10)]
        public decimal DeliveryRatio {
            get {
                return this.DeliveryRatioField;
            }
            set {
                if ((this.DeliveryRatioField.Equals(value) != true)) {
                    this.DeliveryRatioField = value;
                    this.RaisePropertyChanged("DeliveryRatio");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ws.devinosms.com", ConfigurationName="DevinoSms.SmsServiceSoap")]
    public interface SmsServiceSoap {
        
        // CODEGEN: Generating message contract since element name sessionID from namespace http://ws.devinosms.com is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.devinosms.com/GetMessageState", ReplyAction="*")]
        DevinoSender.DevinoSms.GetMessageStateResponse GetMessageState(DevinoSender.DevinoSms.GetMessageStateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.devinosms.com/GetMessageState", ReplyAction="*")]
        System.Threading.Tasks.Task<DevinoSender.DevinoSms.GetMessageStateResponse> GetMessageStateAsync(DevinoSender.DevinoSms.GetMessageStateRequest request);
        
        // CODEGEN: Generating message contract since element name login from namespace http://ws.devinosms.com is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.devinosms.com/GetSessionID", ReplyAction="*")]
        DevinoSender.DevinoSms.GetSessionIDResponse GetSessionID(DevinoSender.DevinoSms.GetSessionIDRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.devinosms.com/GetSessionID", ReplyAction="*")]
        System.Threading.Tasks.Task<DevinoSender.DevinoSms.GetSessionIDResponse> GetSessionIDAsync(DevinoSender.DevinoSms.GetSessionIDRequest request);
        
        // CODEGEN: Generating message contract since element name sessionID from namespace http://ws.devinosms.com is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.devinosms.com/SendMessage", ReplyAction="*")]
        DevinoSender.DevinoSms.SendMessageResponse SendMessage(DevinoSender.DevinoSms.SendMessageRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.devinosms.com/SendMessage", ReplyAction="*")]
        System.Threading.Tasks.Task<DevinoSender.DevinoSms.SendMessageResponse> SendMessageAsync(DevinoSender.DevinoSms.SendMessageRequest request);
        
        // CODEGEN: Generating message contract since element name sessionID from namespace http://ws.devinosms.com is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.devinosms.com/SendMessageByTimeZone", ReplyAction="*")]
        DevinoSender.DevinoSms.SendMessageByTimeZoneResponse SendMessageByTimeZone(DevinoSender.DevinoSms.SendMessageByTimeZoneRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.devinosms.com/SendMessageByTimeZone", ReplyAction="*")]
        System.Threading.Tasks.Task<DevinoSender.DevinoSms.SendMessageByTimeZoneResponse> SendMessageByTimeZoneAsync(DevinoSender.DevinoSms.SendMessageByTimeZoneRequest request);
        
        // CODEGEN: Generating message contract since element name sessionID from namespace http://ws.devinosms.com is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.devinosms.com/SendMessageByTimeZoneToAddresses", ReplyAction="*")]
        DevinoSender.DevinoSms.SendMessageByTimeZoneToAddressesResponse SendMessageByTimeZoneToAddresses(DevinoSender.DevinoSms.SendMessageByTimeZoneToAddressesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.devinosms.com/SendMessageByTimeZoneToAddresses", ReplyAction="*")]
        System.Threading.Tasks.Task<DevinoSender.DevinoSms.SendMessageByTimeZoneToAddressesResponse> SendMessageByTimeZoneToAddressesAsync(DevinoSender.DevinoSms.SendMessageByTimeZoneToAddressesRequest request);
        
        // CODEGEN: Generating message contract since element name sessionID from namespace http://ws.devinosms.com is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.devinosms.com/GetBalance", ReplyAction="*")]
        DevinoSender.DevinoSms.GetBalanceResponse GetBalance(DevinoSender.DevinoSms.GetBalanceRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.devinosms.com/GetBalance", ReplyAction="*")]
        System.Threading.Tasks.Task<DevinoSender.DevinoSms.GetBalanceResponse> GetBalanceAsync(DevinoSender.DevinoSms.GetBalanceRequest request);
        
        // CODEGEN: Generating message contract since element name sessionID from namespace http://ws.devinosms.com is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.devinosms.com/GetIncomingMessages", ReplyAction="*")]
        DevinoSender.DevinoSms.GetIncomingMessagesResponse GetIncomingMessages(DevinoSender.DevinoSms.GetIncomingMessagesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.devinosms.com/GetIncomingMessages", ReplyAction="*")]
        System.Threading.Tasks.Task<DevinoSender.DevinoSms.GetIncomingMessagesResponse> GetIncomingMessagesAsync(DevinoSender.DevinoSms.GetIncomingMessagesRequest request);
        
        // CODEGEN: Generating message contract since element name sessionID from namespace http://ws.devinosms.com is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.devinosms.com/GetStatistics", ReplyAction="*")]
        DevinoSender.DevinoSms.GetStatisticsResponse GetStatistics(DevinoSender.DevinoSms.GetStatisticsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.devinosms.com/GetStatistics", ReplyAction="*")]
        System.Threading.Tasks.Task<DevinoSender.DevinoSms.GetStatisticsResponse> GetStatisticsAsync(DevinoSender.DevinoSms.GetStatisticsRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetMessageStateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetMessageState", Namespace="http://ws.devinosms.com", Order=0)]
        public DevinoSender.DevinoSms.GetMessageStateRequestBody Body;
        
        public GetMessageStateRequest() {
        }
        
        public GetMessageStateRequest(DevinoSender.DevinoSms.GetMessageStateRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ws.devinosms.com")]
    public partial class GetMessageStateRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sessionID;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public long messageID;
        
        public GetMessageStateRequestBody() {
        }
        
        public GetMessageStateRequestBody(string sessionID, long messageID) {
            this.sessionID = sessionID;
            this.messageID = messageID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetMessageStateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetMessageStateResponse", Namespace="http://ws.devinosms.com", Order=0)]
        public DevinoSender.DevinoSms.GetMessageStateResponseBody Body;
        
        public GetMessageStateResponse() {
        }
        
        public GetMessageStateResponse(DevinoSender.DevinoSms.GetMessageStateResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ws.devinosms.com")]
    public partial class GetMessageStateResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public DevinoSender.DevinoSms.SmsMessageStateInfo GetMessageStateResult;
        
        public GetMessageStateResponseBody() {
        }
        
        public GetMessageStateResponseBody(DevinoSender.DevinoSms.SmsMessageStateInfo GetMessageStateResult) {
            this.GetMessageStateResult = GetMessageStateResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetSessionIDRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetSessionID", Namespace="http://ws.devinosms.com", Order=0)]
        public DevinoSender.DevinoSms.GetSessionIDRequestBody Body;
        
        public GetSessionIDRequest() {
        }
        
        public GetSessionIDRequest(DevinoSender.DevinoSms.GetSessionIDRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ws.devinosms.com")]
    public partial class GetSessionIDRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string login;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        public GetSessionIDRequestBody() {
        }
        
        public GetSessionIDRequestBody(string login, string password) {
            this.login = login;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetSessionIDResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetSessionIDResponse", Namespace="http://ws.devinosms.com", Order=0)]
        public DevinoSender.DevinoSms.GetSessionIDResponseBody Body;
        
        public GetSessionIDResponse() {
        }
        
        public GetSessionIDResponse(DevinoSender.DevinoSms.GetSessionIDResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ws.devinosms.com")]
    public partial class GetSessionIDResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetSessionIDResult;
        
        public GetSessionIDResponseBody() {
        }
        
        public GetSessionIDResponseBody(string GetSessionIDResult) {
            this.GetSessionIDResult = GetSessionIDResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendMessageRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendMessage", Namespace="http://ws.devinosms.com", Order=0)]
        public DevinoSender.DevinoSms.SendMessageRequestBody Body;
        
        public SendMessageRequest() {
        }
        
        public SendMessageRequest(DevinoSender.DevinoSms.SendMessageRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ws.devinosms.com")]
    public partial class SendMessageRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sessionID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public DevinoSender.DevinoSms.Message message;
        
        public SendMessageRequestBody() {
        }
        
        public SendMessageRequestBody(string sessionID, DevinoSender.DevinoSms.Message message) {
            this.sessionID = sessionID;
            this.message = message;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendMessageResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendMessageResponse", Namespace="http://ws.devinosms.com", Order=0)]
        public DevinoSender.DevinoSms.SendMessageResponseBody Body;
        
        public SendMessageResponse() {
        }
        
        public SendMessageResponse(DevinoSender.DevinoSms.SendMessageResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ws.devinosms.com")]
    public partial class SendMessageResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public DevinoSender.DevinoSms.ArrayOfString SendMessageResult;
        
        public SendMessageResponseBody() {
        }
        
        public SendMessageResponseBody(DevinoSender.DevinoSms.ArrayOfString SendMessageResult) {
            this.SendMessageResult = SendMessageResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendMessageByTimeZoneRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendMessageByTimeZone", Namespace="http://ws.devinosms.com", Order=0)]
        public DevinoSender.DevinoSms.SendMessageByTimeZoneRequestBody Body;
        
        public SendMessageByTimeZoneRequest() {
        }
        
        public SendMessageByTimeZoneRequest(DevinoSender.DevinoSms.SendMessageByTimeZoneRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ws.devinosms.com")]
    public partial class SendMessageByTimeZoneRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sessionID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string sourceAddress;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string destinationAddress;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string data;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public System.DateTime sendDate;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public System.Nullable<int> validity;
        
        public SendMessageByTimeZoneRequestBody() {
        }
        
        public SendMessageByTimeZoneRequestBody(string sessionID, string sourceAddress, string destinationAddress, string data, System.DateTime sendDate, System.Nullable<int> validity) {
            this.sessionID = sessionID;
            this.sourceAddress = sourceAddress;
            this.destinationAddress = destinationAddress;
            this.data = data;
            this.sendDate = sendDate;
            this.validity = validity;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendMessageByTimeZoneResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendMessageByTimeZoneResponse", Namespace="http://ws.devinosms.com", Order=0)]
        public DevinoSender.DevinoSms.SendMessageByTimeZoneResponseBody Body;
        
        public SendMessageByTimeZoneResponse() {
        }
        
        public SendMessageByTimeZoneResponse(DevinoSender.DevinoSms.SendMessageByTimeZoneResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ws.devinosms.com")]
    public partial class SendMessageByTimeZoneResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public DevinoSender.DevinoSms.ArrayOfString SendMessageByTimeZoneResult;
        
        public SendMessageByTimeZoneResponseBody() {
        }
        
        public SendMessageByTimeZoneResponseBody(DevinoSender.DevinoSms.ArrayOfString SendMessageByTimeZoneResult) {
            this.SendMessageByTimeZoneResult = SendMessageByTimeZoneResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendMessageByTimeZoneToAddressesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendMessageByTimeZoneToAddresses", Namespace="http://ws.devinosms.com", Order=0)]
        public DevinoSender.DevinoSms.SendMessageByTimeZoneToAddressesRequestBody Body;
        
        public SendMessageByTimeZoneToAddressesRequest() {
        }
        
        public SendMessageByTimeZoneToAddressesRequest(DevinoSender.DevinoSms.SendMessageByTimeZoneToAddressesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ws.devinosms.com")]
    public partial class SendMessageByTimeZoneToAddressesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sessionID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string sourceAddress;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public DevinoSender.DevinoSms.ArrayOfString destinationAddresses;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string data;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public System.DateTime sendDate;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public System.Nullable<int> validity;
        
        public SendMessageByTimeZoneToAddressesRequestBody() {
        }
        
        public SendMessageByTimeZoneToAddressesRequestBody(string sessionID, string sourceAddress, DevinoSender.DevinoSms.ArrayOfString destinationAddresses, string data, System.DateTime sendDate, System.Nullable<int> validity) {
            this.sessionID = sessionID;
            this.sourceAddress = sourceAddress;
            this.destinationAddresses = destinationAddresses;
            this.data = data;
            this.sendDate = sendDate;
            this.validity = validity;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendMessageByTimeZoneToAddressesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendMessageByTimeZoneToAddressesResponse", Namespace="http://ws.devinosms.com", Order=0)]
        public DevinoSender.DevinoSms.SendMessageByTimeZoneToAddressesResponseBody Body;
        
        public SendMessageByTimeZoneToAddressesResponse() {
        }
        
        public SendMessageByTimeZoneToAddressesResponse(DevinoSender.DevinoSms.SendMessageByTimeZoneToAddressesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ws.devinosms.com")]
    public partial class SendMessageByTimeZoneToAddressesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public DevinoSender.DevinoSms.ArrayOfString SendMessageByTimeZoneToAddressesResult;
        
        public SendMessageByTimeZoneToAddressesResponseBody() {
        }
        
        public SendMessageByTimeZoneToAddressesResponseBody(DevinoSender.DevinoSms.ArrayOfString SendMessageByTimeZoneToAddressesResult) {
            this.SendMessageByTimeZoneToAddressesResult = SendMessageByTimeZoneToAddressesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetBalanceRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetBalance", Namespace="http://ws.devinosms.com", Order=0)]
        public DevinoSender.DevinoSms.GetBalanceRequestBody Body;
        
        public GetBalanceRequest() {
        }
        
        public GetBalanceRequest(DevinoSender.DevinoSms.GetBalanceRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ws.devinosms.com")]
    public partial class GetBalanceRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sessionID;
        
        public GetBalanceRequestBody() {
        }
        
        public GetBalanceRequestBody(string sessionID) {
            this.sessionID = sessionID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetBalanceResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetBalanceResponse", Namespace="http://ws.devinosms.com", Order=0)]
        public DevinoSender.DevinoSms.GetBalanceResponseBody Body;
        
        public GetBalanceResponse() {
        }
        
        public GetBalanceResponse(DevinoSender.DevinoSms.GetBalanceResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ws.devinosms.com")]
    public partial class GetBalanceResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public decimal GetBalanceResult;
        
        public GetBalanceResponseBody() {
        }
        
        public GetBalanceResponseBody(decimal GetBalanceResult) {
            this.GetBalanceResult = GetBalanceResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetIncomingMessagesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetIncomingMessages", Namespace="http://ws.devinosms.com", Order=0)]
        public DevinoSender.DevinoSms.GetIncomingMessagesRequestBody Body;
        
        public GetIncomingMessagesRequest() {
        }
        
        public GetIncomingMessagesRequest(DevinoSender.DevinoSms.GetIncomingMessagesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ws.devinosms.com")]
    public partial class GetIncomingMessagesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sessionID;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public System.DateTime minDateUTC;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public System.DateTime maxDateUTC;
        
        public GetIncomingMessagesRequestBody() {
        }
        
        public GetIncomingMessagesRequestBody(string sessionID, System.DateTime minDateUTC, System.DateTime maxDateUTC) {
            this.sessionID = sessionID;
            this.minDateUTC = minDateUTC;
            this.maxDateUTC = maxDateUTC;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetIncomingMessagesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetIncomingMessagesResponse", Namespace="http://ws.devinosms.com", Order=0)]
        public DevinoSender.DevinoSms.GetIncomingMessagesResponseBody Body;
        
        public GetIncomingMessagesResponse() {
        }
        
        public GetIncomingMessagesResponse(DevinoSender.DevinoSms.GetIncomingMessagesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ws.devinosms.com")]
    public partial class GetIncomingMessagesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public DevinoSender.DevinoSms.IncomingMessage[] GetIncomingMessagesResult;
        
        public GetIncomingMessagesResponseBody() {
        }
        
        public GetIncomingMessagesResponseBody(DevinoSender.DevinoSms.IncomingMessage[] GetIncomingMessagesResult) {
            this.GetIncomingMessagesResult = GetIncomingMessagesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetStatisticsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetStatistics", Namespace="http://ws.devinosms.com", Order=0)]
        public DevinoSender.DevinoSms.GetStatisticsRequestBody Body;
        
        public GetStatisticsRequest() {
        }
        
        public GetStatisticsRequest(DevinoSender.DevinoSms.GetStatisticsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ws.devinosms.com")]
    public partial class GetStatisticsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sessionID;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public System.DateTime startDateTime;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public System.DateTime endDateTime;
        
        public GetStatisticsRequestBody() {
        }
        
        public GetStatisticsRequestBody(string sessionID, System.DateTime startDateTime, System.DateTime endDateTime) {
            this.sessionID = sessionID;
            this.startDateTime = startDateTime;
            this.endDateTime = endDateTime;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetStatisticsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetStatisticsResponse", Namespace="http://ws.devinosms.com", Order=0)]
        public DevinoSender.DevinoSms.GetStatisticsResponseBody Body;
        
        public GetStatisticsResponse() {
        }
        
        public GetStatisticsResponse(DevinoSender.DevinoSms.GetStatisticsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ws.devinosms.com")]
    public partial class GetStatisticsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public DevinoSender.DevinoSms.DeliveryStatistics GetStatisticsResult;
        
        public GetStatisticsResponseBody() {
        }
        
        public GetStatisticsResponseBody(DevinoSender.DevinoSms.DeliveryStatistics GetStatisticsResult) {
            this.GetStatisticsResult = GetStatisticsResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SmsServiceSoapChannel : DevinoSender.DevinoSms.SmsServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SmsServiceSoapClient : System.ServiceModel.ClientBase<DevinoSender.DevinoSms.SmsServiceSoap>, DevinoSender.DevinoSms.SmsServiceSoap {
        
        public SmsServiceSoapClient() {
        }
        
        public SmsServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SmsServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SmsServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SmsServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DevinoSender.DevinoSms.GetMessageStateResponse DevinoSender.DevinoSms.SmsServiceSoap.GetMessageState(DevinoSender.DevinoSms.GetMessageStateRequest request) {
            return base.Channel.GetMessageState(request);
        }
        
        public DevinoSender.DevinoSms.SmsMessageStateInfo GetMessageState(string sessionID, long messageID) {
            DevinoSender.DevinoSms.GetMessageStateRequest inValue = new DevinoSender.DevinoSms.GetMessageStateRequest();
            inValue.Body = new DevinoSender.DevinoSms.GetMessageStateRequestBody();
            inValue.Body.sessionID = sessionID;
            inValue.Body.messageID = messageID;
            DevinoSender.DevinoSms.GetMessageStateResponse retVal = ((DevinoSender.DevinoSms.SmsServiceSoap)(this)).GetMessageState(inValue);
            return retVal.Body.GetMessageStateResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DevinoSender.DevinoSms.GetMessageStateResponse> DevinoSender.DevinoSms.SmsServiceSoap.GetMessageStateAsync(DevinoSender.DevinoSms.GetMessageStateRequest request) {
            return base.Channel.GetMessageStateAsync(request);
        }
        
        public System.Threading.Tasks.Task<DevinoSender.DevinoSms.GetMessageStateResponse> GetMessageStateAsync(string sessionID, long messageID) {
            DevinoSender.DevinoSms.GetMessageStateRequest inValue = new DevinoSender.DevinoSms.GetMessageStateRequest();
            inValue.Body = new DevinoSender.DevinoSms.GetMessageStateRequestBody();
            inValue.Body.sessionID = sessionID;
            inValue.Body.messageID = messageID;
            return ((DevinoSender.DevinoSms.SmsServiceSoap)(this)).GetMessageStateAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DevinoSender.DevinoSms.GetSessionIDResponse DevinoSender.DevinoSms.SmsServiceSoap.GetSessionID(DevinoSender.DevinoSms.GetSessionIDRequest request) {
            return base.Channel.GetSessionID(request);
        }
        
        public string GetSessionID(string login, string password) {
            DevinoSender.DevinoSms.GetSessionIDRequest inValue = new DevinoSender.DevinoSms.GetSessionIDRequest();
            inValue.Body = new DevinoSender.DevinoSms.GetSessionIDRequestBody();
            inValue.Body.login = login;
            inValue.Body.password = password;
            DevinoSender.DevinoSms.GetSessionIDResponse retVal = ((DevinoSender.DevinoSms.SmsServiceSoap)(this)).GetSessionID(inValue);
            return retVal.Body.GetSessionIDResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DevinoSender.DevinoSms.GetSessionIDResponse> DevinoSender.DevinoSms.SmsServiceSoap.GetSessionIDAsync(DevinoSender.DevinoSms.GetSessionIDRequest request) {
            return base.Channel.GetSessionIDAsync(request);
        }
        
        public System.Threading.Tasks.Task<DevinoSender.DevinoSms.GetSessionIDResponse> GetSessionIDAsync(string login, string password) {
            DevinoSender.DevinoSms.GetSessionIDRequest inValue = new DevinoSender.DevinoSms.GetSessionIDRequest();
            inValue.Body = new DevinoSender.DevinoSms.GetSessionIDRequestBody();
            inValue.Body.login = login;
            inValue.Body.password = password;
            return ((DevinoSender.DevinoSms.SmsServiceSoap)(this)).GetSessionIDAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DevinoSender.DevinoSms.SendMessageResponse DevinoSender.DevinoSms.SmsServiceSoap.SendMessage(DevinoSender.DevinoSms.SendMessageRequest request) {
            return base.Channel.SendMessage(request);
        }
        
        public DevinoSender.DevinoSms.ArrayOfString SendMessage(string sessionID, DevinoSender.DevinoSms.Message message) {
            DevinoSender.DevinoSms.SendMessageRequest inValue = new DevinoSender.DevinoSms.SendMessageRequest();
            inValue.Body = new DevinoSender.DevinoSms.SendMessageRequestBody();
            inValue.Body.sessionID = sessionID;
            inValue.Body.message = message;
            DevinoSender.DevinoSms.SendMessageResponse retVal = ((DevinoSender.DevinoSms.SmsServiceSoap)(this)).SendMessage(inValue);
            return retVal.Body.SendMessageResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DevinoSender.DevinoSms.SendMessageResponse> DevinoSender.DevinoSms.SmsServiceSoap.SendMessageAsync(DevinoSender.DevinoSms.SendMessageRequest request) {
            return base.Channel.SendMessageAsync(request);
        }
        
        public System.Threading.Tasks.Task<DevinoSender.DevinoSms.SendMessageResponse> SendMessageAsync(string sessionID, DevinoSender.DevinoSms.Message message) {
            DevinoSender.DevinoSms.SendMessageRequest inValue = new DevinoSender.DevinoSms.SendMessageRequest();
            inValue.Body = new DevinoSender.DevinoSms.SendMessageRequestBody();
            inValue.Body.sessionID = sessionID;
            inValue.Body.message = message;
            return ((DevinoSender.DevinoSms.SmsServiceSoap)(this)).SendMessageAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DevinoSender.DevinoSms.SendMessageByTimeZoneResponse DevinoSender.DevinoSms.SmsServiceSoap.SendMessageByTimeZone(DevinoSender.DevinoSms.SendMessageByTimeZoneRequest request) {
            return base.Channel.SendMessageByTimeZone(request);
        }
        
        public DevinoSender.DevinoSms.ArrayOfString SendMessageByTimeZone(string sessionID, string sourceAddress, string destinationAddress, string data, System.DateTime sendDate, System.Nullable<int> validity) {
            DevinoSender.DevinoSms.SendMessageByTimeZoneRequest inValue = new DevinoSender.DevinoSms.SendMessageByTimeZoneRequest();
            inValue.Body = new DevinoSender.DevinoSms.SendMessageByTimeZoneRequestBody();
            inValue.Body.sessionID = sessionID;
            inValue.Body.sourceAddress = sourceAddress;
            inValue.Body.destinationAddress = destinationAddress;
            inValue.Body.data = data;
            inValue.Body.sendDate = sendDate;
            inValue.Body.validity = validity;
            DevinoSender.DevinoSms.SendMessageByTimeZoneResponse retVal = ((DevinoSender.DevinoSms.SmsServiceSoap)(this)).SendMessageByTimeZone(inValue);
            return retVal.Body.SendMessageByTimeZoneResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DevinoSender.DevinoSms.SendMessageByTimeZoneResponse> DevinoSender.DevinoSms.SmsServiceSoap.SendMessageByTimeZoneAsync(DevinoSender.DevinoSms.SendMessageByTimeZoneRequest request) {
            return base.Channel.SendMessageByTimeZoneAsync(request);
        }
        
        public System.Threading.Tasks.Task<DevinoSender.DevinoSms.SendMessageByTimeZoneResponse> SendMessageByTimeZoneAsync(string sessionID, string sourceAddress, string destinationAddress, string data, System.DateTime sendDate, System.Nullable<int> validity) {
            DevinoSender.DevinoSms.SendMessageByTimeZoneRequest inValue = new DevinoSender.DevinoSms.SendMessageByTimeZoneRequest();
            inValue.Body = new DevinoSender.DevinoSms.SendMessageByTimeZoneRequestBody();
            inValue.Body.sessionID = sessionID;
            inValue.Body.sourceAddress = sourceAddress;
            inValue.Body.destinationAddress = destinationAddress;
            inValue.Body.data = data;
            inValue.Body.sendDate = sendDate;
            inValue.Body.validity = validity;
            return ((DevinoSender.DevinoSms.SmsServiceSoap)(this)).SendMessageByTimeZoneAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DevinoSender.DevinoSms.SendMessageByTimeZoneToAddressesResponse DevinoSender.DevinoSms.SmsServiceSoap.SendMessageByTimeZoneToAddresses(DevinoSender.DevinoSms.SendMessageByTimeZoneToAddressesRequest request) {
            return base.Channel.SendMessageByTimeZoneToAddresses(request);
        }
        
        public DevinoSender.DevinoSms.ArrayOfString SendMessageByTimeZoneToAddresses(string sessionID, string sourceAddress, DevinoSender.DevinoSms.ArrayOfString destinationAddresses, string data, System.DateTime sendDate, System.Nullable<int> validity) {
            DevinoSender.DevinoSms.SendMessageByTimeZoneToAddressesRequest inValue = new DevinoSender.DevinoSms.SendMessageByTimeZoneToAddressesRequest();
            inValue.Body = new DevinoSender.DevinoSms.SendMessageByTimeZoneToAddressesRequestBody();
            inValue.Body.sessionID = sessionID;
            inValue.Body.sourceAddress = sourceAddress;
            inValue.Body.destinationAddresses = destinationAddresses;
            inValue.Body.data = data;
            inValue.Body.sendDate = sendDate;
            inValue.Body.validity = validity;
            DevinoSender.DevinoSms.SendMessageByTimeZoneToAddressesResponse retVal = ((DevinoSender.DevinoSms.SmsServiceSoap)(this)).SendMessageByTimeZoneToAddresses(inValue);
            return retVal.Body.SendMessageByTimeZoneToAddressesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DevinoSender.DevinoSms.SendMessageByTimeZoneToAddressesResponse> DevinoSender.DevinoSms.SmsServiceSoap.SendMessageByTimeZoneToAddressesAsync(DevinoSender.DevinoSms.SendMessageByTimeZoneToAddressesRequest request) {
            return base.Channel.SendMessageByTimeZoneToAddressesAsync(request);
        }
        
        public System.Threading.Tasks.Task<DevinoSender.DevinoSms.SendMessageByTimeZoneToAddressesResponse> SendMessageByTimeZoneToAddressesAsync(string sessionID, string sourceAddress, DevinoSender.DevinoSms.ArrayOfString destinationAddresses, string data, System.DateTime sendDate, System.Nullable<int> validity) {
            DevinoSender.DevinoSms.SendMessageByTimeZoneToAddressesRequest inValue = new DevinoSender.DevinoSms.SendMessageByTimeZoneToAddressesRequest();
            inValue.Body = new DevinoSender.DevinoSms.SendMessageByTimeZoneToAddressesRequestBody();
            inValue.Body.sessionID = sessionID;
            inValue.Body.sourceAddress = sourceAddress;
            inValue.Body.destinationAddresses = destinationAddresses;
            inValue.Body.data = data;
            inValue.Body.sendDate = sendDate;
            inValue.Body.validity = validity;
            return ((DevinoSender.DevinoSms.SmsServiceSoap)(this)).SendMessageByTimeZoneToAddressesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DevinoSender.DevinoSms.GetBalanceResponse DevinoSender.DevinoSms.SmsServiceSoap.GetBalance(DevinoSender.DevinoSms.GetBalanceRequest request) {
            return base.Channel.GetBalance(request);
        }
        
        public decimal GetBalance(string sessionID) {
            DevinoSender.DevinoSms.GetBalanceRequest inValue = new DevinoSender.DevinoSms.GetBalanceRequest();
            inValue.Body = new DevinoSender.DevinoSms.GetBalanceRequestBody();
            inValue.Body.sessionID = sessionID;
            DevinoSender.DevinoSms.GetBalanceResponse retVal = ((DevinoSender.DevinoSms.SmsServiceSoap)(this)).GetBalance(inValue);
            return retVal.Body.GetBalanceResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DevinoSender.DevinoSms.GetBalanceResponse> DevinoSender.DevinoSms.SmsServiceSoap.GetBalanceAsync(DevinoSender.DevinoSms.GetBalanceRequest request) {
            return base.Channel.GetBalanceAsync(request);
        }
        
        public System.Threading.Tasks.Task<DevinoSender.DevinoSms.GetBalanceResponse> GetBalanceAsync(string sessionID) {
            DevinoSender.DevinoSms.GetBalanceRequest inValue = new DevinoSender.DevinoSms.GetBalanceRequest();
            inValue.Body = new DevinoSender.DevinoSms.GetBalanceRequestBody();
            inValue.Body.sessionID = sessionID;
            return ((DevinoSender.DevinoSms.SmsServiceSoap)(this)).GetBalanceAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DevinoSender.DevinoSms.GetIncomingMessagesResponse DevinoSender.DevinoSms.SmsServiceSoap.GetIncomingMessages(DevinoSender.DevinoSms.GetIncomingMessagesRequest request) {
            return base.Channel.GetIncomingMessages(request);
        }
        
        public DevinoSender.DevinoSms.IncomingMessage[] GetIncomingMessages(string sessionID, System.DateTime minDateUTC, System.DateTime maxDateUTC) {
            DevinoSender.DevinoSms.GetIncomingMessagesRequest inValue = new DevinoSender.DevinoSms.GetIncomingMessagesRequest();
            inValue.Body = new DevinoSender.DevinoSms.GetIncomingMessagesRequestBody();
            inValue.Body.sessionID = sessionID;
            inValue.Body.minDateUTC = minDateUTC;
            inValue.Body.maxDateUTC = maxDateUTC;
            DevinoSender.DevinoSms.GetIncomingMessagesResponse retVal = ((DevinoSender.DevinoSms.SmsServiceSoap)(this)).GetIncomingMessages(inValue);
            return retVal.Body.GetIncomingMessagesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DevinoSender.DevinoSms.GetIncomingMessagesResponse> DevinoSender.DevinoSms.SmsServiceSoap.GetIncomingMessagesAsync(DevinoSender.DevinoSms.GetIncomingMessagesRequest request) {
            return base.Channel.GetIncomingMessagesAsync(request);
        }
        
        public System.Threading.Tasks.Task<DevinoSender.DevinoSms.GetIncomingMessagesResponse> GetIncomingMessagesAsync(string sessionID, System.DateTime minDateUTC, System.DateTime maxDateUTC) {
            DevinoSender.DevinoSms.GetIncomingMessagesRequest inValue = new DevinoSender.DevinoSms.GetIncomingMessagesRequest();
            inValue.Body = new DevinoSender.DevinoSms.GetIncomingMessagesRequestBody();
            inValue.Body.sessionID = sessionID;
            inValue.Body.minDateUTC = minDateUTC;
            inValue.Body.maxDateUTC = maxDateUTC;
            return ((DevinoSender.DevinoSms.SmsServiceSoap)(this)).GetIncomingMessagesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DevinoSender.DevinoSms.GetStatisticsResponse DevinoSender.DevinoSms.SmsServiceSoap.GetStatistics(DevinoSender.DevinoSms.GetStatisticsRequest request) {
            return base.Channel.GetStatistics(request);
        }
        
        public DevinoSender.DevinoSms.DeliveryStatistics GetStatistics(string sessionID, System.DateTime startDateTime, System.DateTime endDateTime) {
            DevinoSender.DevinoSms.GetStatisticsRequest inValue = new DevinoSender.DevinoSms.GetStatisticsRequest();
            inValue.Body = new DevinoSender.DevinoSms.GetStatisticsRequestBody();
            inValue.Body.sessionID = sessionID;
            inValue.Body.startDateTime = startDateTime;
            inValue.Body.endDateTime = endDateTime;
            DevinoSender.DevinoSms.GetStatisticsResponse retVal = ((DevinoSender.DevinoSms.SmsServiceSoap)(this)).GetStatistics(inValue);
            return retVal.Body.GetStatisticsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DevinoSender.DevinoSms.GetStatisticsResponse> DevinoSender.DevinoSms.SmsServiceSoap.GetStatisticsAsync(DevinoSender.DevinoSms.GetStatisticsRequest request) {
            return base.Channel.GetStatisticsAsync(request);
        }
        
        public System.Threading.Tasks.Task<DevinoSender.DevinoSms.GetStatisticsResponse> GetStatisticsAsync(string sessionID, System.DateTime startDateTime, System.DateTime endDateTime) {
            DevinoSender.DevinoSms.GetStatisticsRequest inValue = new DevinoSender.DevinoSms.GetStatisticsRequest();
            inValue.Body = new DevinoSender.DevinoSms.GetStatisticsRequestBody();
            inValue.Body.sessionID = sessionID;
            inValue.Body.startDateTime = startDateTime;
            inValue.Body.endDateTime = endDateTime;
            return ((DevinoSender.DevinoSms.SmsServiceSoap)(this)).GetStatisticsAsync(inValue);
        }
    }
}
