//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRMPhone.SaveWcfService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SaveWcfService.ISaveService")]
    public interface ISaveService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISaveService/SaveFile", ReplyAction="http://tempuri.org/ISaveService/SaveFileResponse")]
        string SaveFile(int requestId, string fileExtension, byte[] fileArray);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISaveService/GetFile", ReplyAction="http://tempuri.org/ISaveService/GetFileResponse")]
        byte[] GetFile(int requestId, string fileName);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISaveServiceChannel : CRMPhone.SaveWcfService.ISaveService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SaveServiceClient : System.ServiceModel.ClientBase<CRMPhone.SaveWcfService.ISaveService>, CRMPhone.SaveWcfService.ISaveService {
        
        public SaveServiceClient() {
        }
        
        public SaveServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SaveServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SaveServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SaveServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string SaveFile(int requestId, string fileExtension, byte[] fileArray) {
            return base.Channel.SaveFile(requestId, fileExtension, fileArray);
        }
        
        public byte[] GetFile(int requestId, string fileName) {
            return base.Channel.GetFile(requestId, fileName);
        }
    }
}
